server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      #url: jdbc:mysql://172.20.10.18:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root123
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  #这里省略MySQL配置信息
  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
        spring:
          #这里省略MySQL配置信息
          #这里省略Redis配置信息
          data:
            mongodb:
              #host: localhost
              #port: 27017
              #database: emos
              #authentication-database: admin
              #username: admin
              #password: abc123456
              uri: mongodb://admin:abc123456@localhost:27017/emos
  # 邮箱连接参数
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 587
    username: 1293360341@qq.com
    password: atneybdhcxwbfhhe
    # 其它参数配置（我是按照教材上配置的，这个 properties 是一个 map）
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#spring boot集成mybatis的方式打印sql
logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
    #com.example.emos.wx.db.dao : debug
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"
emos:
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间（天）
    expire:  5
    #令牌缓存时间（天数）
    cache-expire: 10
  face:
    #createFaceModelUrl: http://172.20.10.19:3000/create_face_model
    #checkinUrl: http://172.20.10.19:3000/checkin
     createFaceModelUrl: http://192.168.31.145:3000/create_face_model
     checkinUrl: http://192.168.31.145:3000/checkin
  email:
    system: heyun.yair@foxmail.com
    hr: 1293360341@qq.com
  image-folder: C:/hy/emos/image
  code: 3E2E7B3FF0944BD2
  #recieveNotify: http://172.20.10.18:8080/emos-wx-api/meeting/recieveNotify
  recieveNotify: http://192.168.31.102:8080/emos-wx-api/meeting/recieveNotify
workflow:
    #url: http://172.20.10.19:9090/emos-workflow
     url: http://192.168.31.145:9090/emos-workflow

wx:
  #app-id: wx83f8fbbf27659300
  #app-secret: 42b9773df65c58e5278d3be27a9be289
  app-id: wx4cb8e9621950da45
  app-secret: 86c4ecfa6be49444ab9b2e9c1490b5aa

trtc:
  appid: 1400737358
  key: b4f9184033fef6938067b17106284869e03734972445c5d3155ffb5d751e9cf9
  expire: 86400








